CREATE DATABASE CONCECIONARIA;
USE CONCECIONARIA;

DROP TABLE `CAR`;
CREATE TABLE CAR (
    id INT (11) NOT NULL AUTO_INCREMENT,

    name VARCHAR (100) DEFAULT NULL,
    color VARCHAR (100) DEFAULT NULL,
    age INT (11) DEFAULT NULL,
    id_model  INT (11) DEFAULT NULL,
    
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL ,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) CHARSET = utf8;

ALTER TABLE CAR ADD CONSTRAINT fk_id_car_modelo FOREIGN KEY (id_model) REFERENCES MODELO (id);

DROP TABLE `MODELO`;
CREATE TABLE MODELO (
    id INT (11) NOT NULL AUTO_INCREMENT,

    name VARCHAR (100) DEFAULT NULL,
    `type` VARCHAR (100) DEFAULT NULL,

    id_author INT (11) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL ,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) CHARSET = utf8;
